### ISSUE TITLE
Doesn't work with sandboxed iframe

### ISSUE THREAD

**Issue by huston007** [jugglinmike/srcdoc-polyfill#11]
i.e. `<iframe sandbox="allow-scripts" srcdoc="<h1>hello</h1>></iframe>`
both IE10 and IE11 won't work

**Comment by jugglinmike** [comment]
Thanks for the report! This is now resolved (via 2e49f27666965465093d71164f64fcbf0902bcb3) and available in [version 1.0.0](https://github.com/jugglinmike/srcdoc-polyfill/releases/tag/v1.0.0).
