### ISSUE TITLE
doesn't work with  IE11

### ISSUE THREAD

**Issue by postme** [jugglinmike/srcdoc-polyfill#12]
included the polyfill js via `<script>` before `</body>`

`<iframe srcdoc="This is a test">``</iframe>`

Not showing anything

most recent IE11 version: 11.0.9600

**Comment by hannesne** [comment]
Just tested this with IE 11.1000.14267 and Edge in Win 10 build 14267, an dit seemed to work fine in both.
In IE11 I did get a warning that IE was restricting script, and I had to allow it. I think this is because I'm running it form a local directory.

**Comment by jugglinmike** [comment]
Thanks, @hannesne!

@postme Can you provide any more information? Is anything printed to the developer's console, for instance? Or could you step through the polyfill's execution with a `debugger` statement?

**Comment by chrisi1698** [comment]
Hello!
I have the same problem actually -- in the console I get the following error message:
"File: srcdoc-polyfill.min.js, Line: 4, Column: 535", the debugger highlights "(a.contentWindow.location=c)" in the code view. I hope this helps. Great script though anyways, thank you very much!
BR, Chris

**Comment by chrisi1698** [comment]
OH MY... it was the "sandbox" attribute. I had it set on the iframes... removing it, it works now.

**Comment by jugglinmike** [comment]
@chrisi1698 Thanks for the info, @chrisi1698. I've opened gh-13 to remind me to document the incompatibility with the "sandbox" attribute, so hopefully no one has to struggle with that in the future.

**Comment by jugglinmike** [comment]
Since we haven't heard back from the original reporter in over a year, but we do have independent confirmation of proper functioning in IE11, I'm going to close this issue. If anyone has any more information about this bug, then please post it here and we will continue the investigation.
